# Generated by Django 2.2.2 on 2023-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='react',
            name='reacted_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='react',
            name='reacted_by_id',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
