# Generated by Django 2.2.2 on 2023-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0004_auto_20230215_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='reacted_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
