# Generated by Django 2.2.2 on 2023-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0005_auto_20230215_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='react',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
